name: Codesign Quick Testing Workflow
env:
  OPENROAD_PREINSTALLED: 1
  PREINSTALLED_OPENROAD_PATH: "/scratch/openroad_executable/openroad"
  SCALEHLS_PREINSTALLED: 1
  PREINSTALLED_SCALEHLS_PATH: "/scratch/seunghyeok/codesign/ScaleHLS-HIDA"
  STREAMHLS_PREINSTALLED: 1
  PREINSTALLED_STREAMHLS_PATH: "/scratch/seunghyeok/Stream-HLS"


on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
      - main
jobs:
    test:
        name: Codesign Quick Test
        runs-on: self-hosted
        steps:
          - name: Remove old workspace
            run: |
              rm -rf *
              rm -rf .[^.] .??*
              ls -la

          - name: Debug-echo
            run: |
              echo ">>> CI is running inside Python Tests workflow on $(date)"
              echo "Current directory: $(pwd)"
              ls -la

          - name: Check out repository
            uses: actions/checkout@v5

          - name: Debug-echo
            run: |
              echo ">>> CI is running inside Python Tests workflow on $(date)"
              echo "Current directory: $(pwd)"
              ls -la

          - name: Update PATH and PYTHONPATH for ScaleHLS
            run: |
              # Add the ScaleHLS and Polygeist binaries to the system PATH
              echo "${{ env.PREINSTALLED_SCALEHLS_PATH }}/build/bin" >> $GITHUB_PATH
              echo "${{ env.PREINSTALLED_SCALEHLS_PATH }}/polygeist/build/bin" >> $GITHUB_PATH
              
              # Add the ScaleHLS python packages to PYTHONPATH for the runner
              echo "PYTHONPATH=$PYTHONPATH:${{ env.PREINSTALLED_SCALEHLS_PATH }}/build/tools/scalehls/python_packages/scalehls_core" >> $GITHUB_ENV

          - name: Start Env
            run: ./full_env_start.sh

          - name: Run regressions
            run: |
              chmod +x test/automated_test_scripts/automated-scripts.sh || true
              ./test/automated_test_scripts/automated-scripts.sh

          - name: Confirm End
            run: echo "Quick Test Done"